#!/usr/bin/env bash
#
# Combine the per-platform manifest fragments written by package_local.sh
# into the single orc-plugin-manifest.yaml published with a release.
#
# Mirrors orc-plugin_skeleton's scripts/merge_manifests.sh verbatim — this
# script is entirely generic (it only reads plugin_id/plugin_version/
# artifacts out of whatever fragments it's given), so there is nothing
# plugin-specific to adapt here.
#
# Usage: merge_manifests.sh <output-file> <fragment.yaml> [fragment.yaml ...]

set -euo pipefail

if [[ $# -lt 2 ]]; then
    echo "Usage: $0 <output-file> <fragment.yaml> [fragment.yaml ...]"
    exit 1
fi

output="$1"
shift

# Header fields come from the first fragment; every fragment is generated
# from the same descriptor, so a disagreement means the matrix built
# mismatched sources and the release must not be published.
# Fragments built on Windows can arrive with CRLF line endings, so every field
# is read with the trailing CR stripped: an invisible difference must not read
# as mismatched sources, and must not reach the published manifest.
first="$1"
plugin_id="$(awk -F': ' '/^plugin_id:/ {sub(/\r$/, "", $2); print $2; exit}' "$first")"
plugin_version="$(awk -F': ' '/^plugin_version:/ {sub(/\r$/, "", $2); print $2; exit}' "$first")"

if [[ -z "$plugin_id" || -z "$plugin_version" ]]; then
    echo "Fragment $first is missing plugin_id or plugin_version"
    exit 1
fi

{
    echo "# Generated by scripts/merge_manifests.sh - do not edit by hand."
    echo "manifest_schema: 1"
    echo "plugin_id: ${plugin_id}"
    echo "plugin_version: ${plugin_version}"
    echo "artifacts:"
} > "$output"

for fragment in "$@"; do
    fragment_id="$(awk -F': ' '/^plugin_id:/ {sub(/\r$/, "", $2); print $2; exit}' "$fragment")"
    fragment_version="$(awk -F': ' '/^plugin_version:/ {sub(/\r$/, "", $2); print $2; exit}' "$fragment")"

    if [[ "$fragment_id" != "$plugin_id" || "$fragment_version" != "$plugin_version" ]]; then
        echo "Fragment $fragment disagrees with $first: ${fragment_id} ${fragment_version}"
        exit 1
    fi

    # Everything after the "artifacts:" line is this platform's artifact list.
    awk '/^artifacts:/ {found = 1; next} found {sub(/\r$/, ""); print}' "$fragment" >> "$output"
done

if ! grep -q '^  - file: ' "$output"; then
    echo "Merged manifest declares no artifacts"
    exit 1
fi

echo "Wrote $output"
cat "$output"
