#!/usr/bin/env python3
"""Merge per-platform fragments (gen_manifest_fragment.py) into the final
orc-plugin-manifest.yaml uploaded with the GitHub release.

No YAML library dependency on purpose: the manifest's shape is fixed and
small (see docs/technical/plugin-architecture.md#release-manifest in the
decode-orc host repo, or plugin_release_manifest.h's parser, which is the
authoritative source of truth for the field names below), so a small
hand-rolled emitter is simpler and has one fewer moving part in CI than
pulling in PyYAML.
"""
import argparse
import glob
import json
import sys
from pathlib import Path

MANIFEST_SCHEMA = 1


def yaml_str(s: str) -> str:
    """Quote a scalar only when YAML would otherwise misparse it (e.g. a
    toolchain tag like gcc14/libstdc++ is fine bare; anything with a colon
    or leading special character isn't)."""
    if s == "" or any(c in s for c in ":#{}[]&*!|>'\"%@`") or s[0] in "-?":
        return json.dumps(s)  # valid YAML flow scalar too
    return s


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("fragments", nargs="+",
                     help="Glob pattern(s) for the per-platform JSON fragments "
                          "written by gen_manifest_fragment.py")
    ap.add_argument("--plugin-version", required=True,
                     help="Release version (e.g. from the git tag, without the leading 'v')")
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    paths = []
    for pattern in args.fragments:
        paths.extend(sorted(glob.glob(pattern, recursive=True)))
    if not paths:
        print(f"error: no fragment files matched {args.fragments}", file=sys.stderr)
        return 1

    fragments = []
    for p in paths:
        with open(p) as f:
            fragments.append(json.load(f))

    plugin_ids = {f["plugin_id"] for f in fragments}
    if len(plugin_ids) != 1:
        print(f"error: fragments disagree on plugin_id: {plugin_ids}", file=sys.stderr)
        return 1
    plugin_id = plugin_ids.pop()

    platforms = [f["platform"] for f in fragments]
    if len(platforms) != len(set(platforms)):
        print(f"error: duplicate platform among fragments: {platforms}", file=sys.stderr)
        return 1

    lines = [
        "# Generated by scripts/merge_manifest_fragments.py from the per-platform",
        "# fragments produced by scripts/gen_manifest_fragment.py — do not edit by hand.",
        f"manifest_schema: {MANIFEST_SCHEMA}",
        f"plugin_id: {yaml_str(plugin_id)}",
        f"plugin_version: {yaml_str(args.plugin_version)}",
        "artifacts:",
    ]
    for f in sorted(fragments, key=lambda x: x["platform"]):
        lines.append(f"  - file: {yaml_str(f['file'])}")
        lines.append(f"    platform: {yaml_str(f['platform'])}")
        lines.append(f"    abi: {int(f['abi'])}")
        lines.append(f"    toolchain_tag: {yaml_str(f['toolchain_tag'])}")
        lines.append(f"    sha256: {yaml_str(f['sha256'])}")

    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out} ({len(fragments)} artifact(s), plugin_id={plugin_id})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
