#!/usr/bin/env bash
#
# Package the built plugin as a release asset and emit the per-platform
# release-manifest fragment that goes with it.
#
# Since host ABI 12 every plugin release must publish an
# orc-plugin-manifest.yaml declaring each binary's platform, host ABI,
# toolchain tag and SHA-256 digest; a release without one cannot be browsed,
# installed, or updated to. This script writes one platform's worth of that
# manifest; scripts/merge_manifests.sh combines the per-platform fragments
# into the single asset published with the release.
#
# Mirrors orc-plugin_skeleton's scripts/package_local.sh, adapted for the
# plugin target name (orc-stage-plugin-hvd-chroma-decoder) here.
#
# Usage: package_local.sh <build-dir> [output-dir]

set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <build-dir> [output-dir]"
    exit 1
fi

build_dir="$1"
output_dir="${2:-dist}"

mkdir -p "$output_dir"

case "$(uname -s)" in
    Linux)
        platform="linux"
        ext="so"
        exe_ext=""
        ;;
    Darwin)
        platform="macos"
        ext="dylib"
        exe_ext=""
        ;;
    MINGW*|MSYS*|CYGWIN*)
        platform="windows"
        ext="dll"
        exe_ext=".exe"
        ;;
    *)
        echo "Unsupported platform"
        exit 1
        ;;
esac

# --- Build facts, straight from the compiled descriptor -------------------

build_info="$(find "$build_dir" -type f -name "orc-plugin-build-info${exe_ext}" | head -n 1)"

if [[ -z "$build_info" ]]; then
    echo "Could not locate orc-plugin-build-info in $build_dir"
    echo "(build the project first; it is built unconditionally)"
    exit 1
fi

plugin_id=""
plugin_version=""
stage_name=""
abi=""
toolchain_tag=""

# orc-plugin-build-info writes its lines with "\n", but a Windows build prints
# them through a text-mode stdout, so every value would otherwise arrive with a
# trailing CR and end up embedded in this platform's manifest fragment. That
# difference is invisible in the YAML and only surfaces when merge_manifests.sh
# compares the Windows fragment against the Linux one at release time.

while IFS='=' read -r key value; do
    case "$key" in
        plugin_id)      plugin_id="$value" ;;
        plugin_version) plugin_version="$value" ;;
        stage_name)     stage_name="$value" ;;
        abi)            abi="$value" ;;
        toolchain_tag)  toolchain_tag="$value" ;;
    esac
done < <("$build_info" | tr -d '\r')

for required in plugin_id plugin_version stage_name abi toolchain_tag; do
    if [[ -z "${!required}" ]]; then
        echo "orc-plugin-build-info did not report $required"
        exit 1
    fi
done

# --- Copy the binary under the release-asset name -------------------------
#
# orc-plugin_<stage-name>_<platform>[_abi<N>].<ext> is the artifact naming
# convention the host validates downloads against. The _abi<N> token lets one
# release carry builds for several host ABIs side by side.

plugin_name="orc-plugin_${stage_name}_${platform}_abi${abi}.${ext}"

candidate="$(find "$build_dir" -type f \( -name "*orc-stage-plugin-hvd-chroma-decoder*.${ext}" -o -name "orc-stage-plugin-hvd-chroma-decoder.${ext}" \) | head -n 1)"

if [[ -z "$candidate" ]]; then
    echo "Could not locate built plugin binary in $build_dir"
    exit 1
fi

cp "$candidate" "$output_dir/$plugin_name"

# --- Digest ---------------------------------------------------------------

if command -v sha256sum >/dev/null 2>&1; then
    sha256="$(sha256sum "$output_dir/$plugin_name" | awk '{print $1}')"
elif command -v shasum >/dev/null 2>&1; then
    sha256="$(shasum -a 256 "$output_dir/$plugin_name" | awk '{print $1}')"
else
    echo "Neither sha256sum nor shasum is available; cannot digest the artifact"
    exit 1
fi

# --- Manifest fragment ----------------------------------------------------
#
# A complete, valid single-platform manifest: publishing a one-platform
# release can use it as-is. Fragment names deliberately do not start with
# orc-plugin_, so CI's release-asset glob never picks them up directly.

manifest_fragment="$output_dir/plugin-manifest-${platform}.yaml"

cat > "$manifest_fragment" <<EOF
# Generated by scripts/package_local.sh - do not edit by hand.
manifest_schema: 1
plugin_id: ${plugin_id}
plugin_version: ${plugin_version}
artifacts:
  - file: ${plugin_name}
    platform: ${platform}
    abi: ${abi}
    toolchain_tag: ${toolchain_tag}
    sha256: ${sha256}
EOF

echo "Packaged: $output_dir/$plugin_name"
echo "Manifest fragment: $manifest_fragment"
